M48
; DRILL file {KiCad 9.0.6} date 2026-01-26T19:54:05-0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-26T19:54:05-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C4.000
%
G90
G05
T1
X239.3Y-98.31
X239.3Y-105.31
T2
X193.62Y-97.75
X203.78Y-97.75
X213.88Y-97.91
X224.04Y-97.91
T3
X198.7Y-97.75
X218.96Y-97.91
M30
